import type { AiPersonalityId } from "../domain/AiPersonality";
import type {
  FactionIdentity,
  FactionKind,
  FactionOrigin,
} from "../domain/FactionRoster";

// Names identify historical polities/peoples or fictional communities. The AI
// associations are authored game archetypes, not claims about inherent traits.
// "Tribe" is a gameplay size/rules category, not an ethnographic classification.
export const FACTION_REFERENCES = {
  ancient: {
    title: "Ancient powers and their regional histories",
    url: "https://en.wikipedia.org/wiki/List_of_ancient_great_powers",
  },
  mesopotamia: {
    title: "Kingdoms and empires of Mesopotamia",
    url: "https://www.worldhistory.org/collection/173/kingdoms--empires-of-ancient-mesopotamia/",
  },
  china: {
    title: "Ancient China",
    url: "https://openstax.org/books/world-history-volume-1/pages/5-1-ancient-china",
  },
  india: {
    title: "Gupta Empire and earlier Indian polities",
    url: "https://www.worldhistory.org/Gupta_Empire/",
  },
  africa: {
    title: "Medieval sub-Saharan Africa",
    url: "https://openstax.org/books/world-history-volume-1/pages/15-2-medieval-sub-saharan-africa",
  },
  westAfrica: {
    title: "The empires of West Africa",
    url: "https://www.worldhistory.org/collection/61/the-empires-of-west-africa/",
  },
  americas: {
    title: "Pre-Columbian cultures",
    url: "https://en.wikipedia.org/wiki/List_of_pre-Columbian_cultures",
  },
  celtic: {
    title: "Ancient Celtic peoples and tribes",
    url: "https://en.wikipedia.org/wiki/List_of_ancient_Celtic_peoples_and_tribes",
  },
  germanic: {
    title: "Early Germanic peoples",
    url: "https://en.wikipedia.org/wiki/List_of_early_Germanic_peoples",
  },
  steppe: {
    title: "Sarmatians and related steppe peoples",
    url: "https://en.wikipedia.org/wiki/Sarmatians",
  },
  medieval: {
    title: "Medieval states by region",
    url: "https://en.wikipedia.org/wiki/List_of_states_during_the_Middle_Ages",
  },
  italic: {
    title: "Etruscan civilization and neighboring Italian peoples",
    url: "https://www.worldhistory.org/Etruscan_Civilization/",
  },
  elven: {
    title: "Elven realms",
    url: "https://tolkiengateway.net/wiki/Category:Elven_realms",
  },
  mannish: {
    title: "Mannish realms",
    url: "https://tolkiengateway.net/wiki/Category:Mannish_realms",
  },
  dwarven: {
    title: "Dwarven kindreds and realms",
    url: "https://tolkiengateway.net/wiki/Dwarves",
  },
  darkRealms: {
    title: "Realms of Middle-earth",
    url: "https://tolkiengateway.net/wiki/Category:Realms",
  },
  men: {
    title: "Peoples of Middle-earth",
    url: "https://tolkiengateway.net/wiki/Men",
  },
  beornings: {
    title: "Beornings",
    url: "https://tolkiengateway.net/wiki/Beornings",
  },
  dru: {
    title: "Drúedain",
    url: "https://tolkiengateway.net/wiki/Dr%C3%BAedain",
  },
  rohan: { title: "Rohan", url: "https://tolkiengateway.net/wiki/Rohan" },
  umbar: { title: "Umbar", url: "https://tolkiengateway.net/wiki/Umbar" },
  houses: {
    title: "Houses of Westeros",
    url: "https://awoiaf.westeros.org/index.php/List_of_Houses",
  },
  cities: {
    title: "The Nine Free Cities",
    url: "https://www.westeros.org/Citadel/Concordance/Section/12.2./",
  },
  essos: {
    title: "Realms and cities of Essos",
    url: "https://awoiaf.westeros.org/index.php/Essos",
  },
  qarth: { title: "Qarth", url: "https://awoiaf.westeros.org/index.php/Qarth" },
  yiTi: { title: "Yi Ti", url: "https://awoiaf.westeros.org/index.php/Yi_Ti" },
  slaverCities: {
    title: "Cities of Slaver's Bay",
    url: "https://awoiaf.westeros.org/index.php/Slaver_Cities",
  },
  kingdoms: {
    title: "Kingdoms of Westeros",
    url: "https://www.westeros.org/Citadel/FAQ/Category/C159",
  },
  freeFolk: {
    title: "Free folk clans",
    url: "https://awoiaf.westeros.org/index.php/Free_folk",
  },
  dothraki: {
    title: "Dothraki",
    url: "https://awoiaf.westeros.org/index.php/Dothraki",
  },
  valeClans: {
    title: "Vale mountain clans",
    url: "https://awoiaf.westeros.org/index.php/Vale_mountain_clans",
  },
  hobbits: {
    title: "Hobbit communities",
    url: "https://tolkiengateway.net/wiki/Hobbits",
  },
  haudenosaunee: {
    title: "Haudenosaunee nations",
    url: "https://americanindian.si.edu/nk360/resources/Haudenosaunee-Guide-for-Educators.cshtml",
  },
  sahara: {
    title: "Saharan peoples and caravan networks",
    url: "https://www.worldhistory.org/article/1344/the-camel-caravans-of-the-ancient-sahara/",
  },
  songhaiPeoples: {
    title: "Peoples of the Songhai Empire",
    url: "https://www.worldhistory.org/Songhai_Empire/",
  },
  hausa: { title: "Hausaland", url: "https://www.worldhistory.org/Hausaland/" },
  muisca: {
    title: "Muisca civilization",
    url: "https://www.worldhistory.org/Muisca_Civilization/",
  },
} as const;

function group(
  kind: FactionKind,
  origin: FactionOrigin,
  region: string,
  references: readonly (keyof typeof FACTION_REFERENCES)[],
  personalities: readonly AiPersonalityId[],
  names: readonly string[],
): FactionIdentity[] {
  return names.map((name) =>
    Object.freeze({
      id: `${origin}:${name
        .normalize("NFD")
        .replace(/[\u0300-\u036f]/g, "")
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "")}`,
      name,
      kind,
      origin,
      region,
      references,
      personalities,
    }),
  );
}

export const FACTIONS: readonly FactionIdentity[] = [
  ...group(
    "regular",
    "middle-earth",
    "Hobbit settlements",
    ["hobbits"],
    ["builder", "diplomat"],
    ["The Shire", "Buckland"],
  ),
  ...group(
    "tribe",
    "middle-earth",
    "Hobbit communities",
    ["hobbits"],
    ["warden", "balanced"],
    ["Harfoots", "Stoors", "Fallohides"],
  ),
  ...group(
    "tribe",
    "historical",
    "Northeastern North America",
    ["haudenosaunee"],
    ["warden", "balanced"],
    [
      "Haudenosaunee",
      "Mohawk",
      "Oneida",
      "Onondaga",
      "Cayuga",
      "Seneca",
      "Tuscarora",
    ],
  ),
  ...group(
    "tribe",
    "historical",
    "Saharan and West African communities",
    ["sahara", "songhaiPeoples", "hausa"],
    ["balanced", "warden", "skirmisher"],
    ["Garamantes", "Tuareg", "Sanhaja", "Mossi", "Mande", "Fulbe", "Hausa"],
  ),
  ...group(
    "tribe",
    "historical",
    "Mesoamerican and Andean communities",
    ["americas", "muisca"],
    ["warden", "balanced", "skirmisher"],
    [
      "Muisca",
      "Mixtec",
      "Zapotec",
      "Mexica",
      "K'iche'",
      "Kaqchikel",
      "Aymara",
      "Quechua",
      "Taíno",
      "Chachapoya",
    ],
  ),
  ...group(
    "regular",
    "historical",
    "Mesopotamia and the ancient Near East",
    ["ancient", "mesopotamia"],
    ["conqueror", "engineer"],
    [
      "Akkadian Empire",
      "Assyria",
      "Babylonia",
      "Hittite Empire",
      "Mitanni",
      "Urartu",
      "Elam",
      "Achaemenid Persia",
      "Parthia",
      "Sasanian Persia",
    ],
  ),
  ...group(
    "regular",
    "historical",
    "Ancient cities and eastern Mediterranean",
    ["ancient", "mesopotamia"],
    ["builder", "scholar"],
    [
      "Ur",
      "Uruk",
      "Lagash",
      "Kish",
      "Mari",
      "Ebla",
      "Ugarit",
      "Ancient Egypt",
      "Lydia",
      "Phrygia",
      "Armenia",
      "Pontus",
      "Cappadocia",
      "Commagene",
    ],
  ),
  ...group(
    "regular",
    "historical",
    "Mediterranean sea powers",
    ["ancient"],
    ["merchant", "diplomat"],
    [
      "Phoenicia",
      "Tyre",
      "Sidon",
      "Carthage",
      "Athens",
      "Corinth",
      "Rhodes",
      "Syracuse",
      "Massalia",
      "Nabataea",
    ],
  ),
  ...group(
    "regular",
    "historical",
    "Classical Mediterranean",
    ["ancient"],
    ["conqueror", "balanced"],
    [
      "Rome",
      "Macedon",
      "Seleucid Empire",
      "Ptolemaic Egypt",
      "Pergamon",
      "Epirus",
      "Bactria",
      "Bosporan Kingdom",
      "Numidia",
      "Sparta",
      "Thebes",
      "Thrace",
    ],
  ),
  ...group(
    "regular",
    "historical",
    "Indian subcontinent",
    ["ancient", "india"],
    ["scholar", "builder"],
    [
      "Magadha",
      "Kosala",
      "Avanti",
      "Gandhara",
      "Mauryan Empire",
      "Gupta Empire",
      "Satavahana Kingdom",
      "Kushan Empire",
      "Chola Kingdom",
      "Pandya Kingdom",
      "Chera Kingdom",
      "Pallava Kingdom",
      "Pala Empire",
      "Chalukya Kingdom",
    ],
  ),
  ...group(
    "regular",
    "historical",
    "East Asia",
    ["ancient", "china"],
    ["builder", "conqueror"],
    [
      "Shang Dynasty",
      "Zhou Dynasty",
      "Qin Empire",
      "Han Empire",
      "Tang Empire",
      "Song Dynasty",
      "Goguryeo",
      "Baekje",
      "Silla",
      "Yamato",
      "Goryeo",
    ],
  ),
  ...group(
    "regular",
    "historical",
    "Southeast Asia",
    ["ancient", "medieval"],
    ["merchant", "builder"],
    [
      "Funan",
      "Champa",
      "Khmer Empire",
      "Srivijaya",
      "Majapahit",
      "Pagan Kingdom",
      "Sukhothai",
      "Dai Viet",
    ],
  ),
  ...group(
    "regular",
    "historical",
    "Africa",
    ["africa", "westAfrica", "ancient"],
    ["merchant", "builder"],
    [
      "Kush",
      "Kerma",
      "Aksum",
      "Ghana Empire",
      "Mali Empire",
      "Songhai Empire",
      "Kanem-Bornu",
      "Benin Kingdom",
      "Ife",
      "Great Zimbabwe",
      "Kilwa Sultanate",
      "Makuria",
      "Alodia",
      "Mapungubwe",
    ],
  ),
  ...group(
    "regular",
    "historical",
    "Americas before European colonization",
    ["americas"],
    ["builder", "conqueror"],
    [
      "Aztec Empire",
      "Inca Empire",
      "Tikal",
      "Calakmul",
      "Palenque",
      "Copán",
      "Chichén Itzá",
      "Mayapan",
      "Teotihuacan",
      "Monte Albán",
      "Tarascan State",
      "Chimor",
      "Moche",
      "Wari",
      "Tiwanaku",
      "Cahokia",
    ],
  ),
  ...group(
    "regular",
    "historical",
    "Eurasian mounted empires",
    ["ancient", "steppe", "medieval"],
    ["rider", "conqueror"],
    [
      "Scythia",
      "Sarmatia",
      "Xiongnu",
      "Hunnic Empire",
      "Göktürk Khaganate",
      "Avar Khaganate",
      "Khazar Khaganate",
      "Mongol Empire",
      "Golden Horde",
      "Timurid Empire",
    ],
  ),
  ...group(
    "regular",
    "historical",
    "Early and high medieval realms",
    ["medieval"],
    ["warden", "balanced"],
    [
      "Byzantine Empire",
      "Frankish Kingdom",
      "Visigothic Kingdom",
      "Ostrogothic Kingdom",
      "Lombard Kingdom",
      "Burgundian Kingdom",
      "Wessex",
      "Mercia",
      "Northumbria",
      "Alba",
      "Kingdom of Norway",
      "Kievan Rus",
      "First Bulgarian Empire",
      "Kingdom of Hungary",
      "Kingdom of Poland",
      "Kingdom of Bohemia",
      "Kingdom of Georgia",
    ],
  ),
  ...group(
    "regular",
    "historical",
    "Medieval trade and administration",
    ["medieval"],
    ["merchant", "diplomat"],
    [
      "Republic of Venice",
      "Republic of Genoa",
      "Hanseatic League",
      "Umayyad Caliphate",
      "Abbasid Caliphate",
      "Fatimid Caliphate",
      "Ayyubid Sultanate",
      "Seljuk Empire",
      "Almoravid Empire",
      "Almohad Caliphate",
      "Delhi Sultanate",
    ],
  ),
  ...group(
    "tribe",
    "historical",
    "Gaul and neighboring peoples",
    ["celtic"],
    ["balanced", "conqueror", "warden"],
    [
      "Aedui",
      "Arverni",
      "Belgae",
      "Boii",
      "Carnutes",
      "Helvetii",
      "Nervii",
      "Remi",
      "Sequani",
      "Senones",
      "Parisii",
      "Treveri",
      "Veneti",
      "Allobroges",
      "Bituriges",
      "Lingones",
      "Eburones",
      "Volcae",
      "Taurisci",
      "Scordisci",
      "Tectosages",
      "Tolistobogii",
      "Trocmi",
    ],
  ),
  ...group(
    "tribe",
    "historical",
    "Britain and Iberia",
    ["celtic"],
    ["warden", "skirmisher", "balanced"],
    [
      "Iceni",
      "Brigantes",
      "Trinovantes",
      "Catuvellauni",
      "Silures",
      "Ordovices",
      "Dumnonii",
      "Caledonii",
      "Picts",
      "Dál Riata",
      "Lusitanians",
      "Celtiberians",
      "Arevaci",
      "Vaccaei",
      "Vettones",
      "Cantabri",
      "Astures",
      "Turdetani",
      "Gallaeci",
      "Vascones",
    ],
  ),
  ...group(
    "tribe",
    "historical",
    "Germania and northern Europe",
    ["germanic"],
    ["conqueror", "warden", "balanced"],
    [
      "Cherusci",
      "Chatti",
      "Suebi",
      "Marcomanni",
      "Quadi",
      "Batavi",
      "Frisii",
      "Chauci",
      "Bructeri",
      "Usipetes",
      "Tencteri",
      "Sicambri",
      "Semnones",
      "Hermunduri",
      "Alemanni",
      "Saxons",
      "Angles",
      "Jutes",
      "Goths",
      "Vandals",
      "Gepids",
      "Heruli",
      "Rugii",
      "Burgundians",
      "Lombards",
      "Franks",
    ],
  ),
  ...group(
    "tribe",
    "historical",
    "Steppe and ancient border peoples",
    ["ancient", "steppe"],
    ["conqueror", "balanced", "skirmisher"],
    [
      "Alans",
      "Saka",
      "Massagetae",
      "Dahae",
      "Cimmerians",
      "Sarmatians",
      "Roxolani",
      "Iazyges",
      "Dacians",
      "Getae",
      "Illyrians",
      "Odrysians",
      "Triballi",
      "Paeonians",
    ],
  ),
  ...group(
    "tribe",
    "historical",
    "Ancient Italy",
    ["italic", "ancient"],
    ["warden", "balanced", "conqueror"],
    [
      "Etruscans",
      "Samnites",
      "Sabines",
      "Latins",
      "Umbrians",
      "Picentes",
      "Ligurians",
    ],
  ),
  ...group(
    "tribe",
    "historical",
    "Ancient Near Eastern communities",
    ["ancient"],
    ["warden", "balanced"],
    [
      "Amorites",
      "Hurrians",
      "Arameans",
      "Edomites",
      "Moabites",
      "Ammonites",
      "Philistines",
      "Luwians",
      "Lycians",
      "Carians",
      "Medes",
      "Lullubi",
      "Gutians",
    ],
  ),
  ...group(
    "tribe",
    "historical",
    "Early Asian communities",
    ["ancient", "india", "china"],
    ["balanced", "skirmisher", "warden"],
    [
      "Yuezhi",
      "Wusun",
      "Xianbei",
      "Rouran",
      "Khitan",
      "Jurchen",
      "Qiang",
      "Shakya",
      "Licchavi",
      "Malla",
      "Kuru",
      "Panchala",
      "Kamboja",
    ],
  ),
  ...group(
    "regular",
    "middle-earth",
    "Realms of Men",
    ["mannish", "rohan"],
    ["warden", "diplomat"],
    ["Gondor", "Arnor", "Arthedain", "Cardolan", "Dale", "Dol Amroth"],
  ),
  ...group(
    "regular",
    "middle-earth",
    "Mounted and eastern realms",
    ["mannish", "rohan", "men"],
    ["rider", "conqueror"],
    ["Rohan", "Khand", "Rhûn", "Harad", "Rhovanion"],
  ),
  ...group(
    "regular",
    "middle-earth",
    "Trading settlements",
    ["mannish"],
    ["merchant", "diplomat"],
    ["Lake-town", "Bree-land"],
  ),
  ...group(
    "regular",
    "middle-earth",
    "Sea kingdoms",
    ["mannish", "umbar"],
    ["admiral", "merchant"],
    ["Númenor", "Umbar"],
  ),
  ...group(
    "regular",
    "middle-earth",
    "Elven realms",
    ["elven"],
    ["skirmisher", "scholar"],
    [
      "Lothlórien",
      "Rivendell",
      "Lindon",
      "Woodland Realm",
      "Doriath",
      "Gondolin",
      "Nargothrond",
      "Eregion",
      "Falas",
      "Hithlum",
      "Nevrast",
    ],
  ),
  ...group(
    "regular",
    "middle-earth",
    "Dwarven realms",
    ["dwarven"],
    ["builder", "engineer"],
    [
      "Erebor",
      "Khazad-dûm",
      "Iron Hills",
      "Blue Mountains",
      "Nogrod",
      "Belegost",
    ],
  ),
  ...group(
    "regular",
    "middle-earth",
    "Fortresses of the Shadow",
    ["darkRealms", "mannish"],
    ["conqueror", "engineer"],
    ["Mordor", "Isengard", "Angmar", "Dol Guldur", "Gundabad", "Rhudaur"],
  ),
  ...group(
    "tribe",
    "middle-earth",
    "Mannish communities",
    ["men", "beornings", "dru"],
    ["warden", "skirmisher", "balanced"],
    [
      "Beornings",
      "Woodmen",
      "Drúedain",
      "Dunlendings",
      "Lossoth",
      "Haladin",
      "House of Bëor",
      "House of Hador",
      "Dúnedain Rangers",
      "Bardings",
    ],
  ),
  ...group(
    "tribe",
    "middle-earth",
    "Eastern and southern hosts",
    ["men", "umbar"],
    ["conqueror", "balanced"],
    [
      "Easterlings",
      "Haradrim",
      "Variags",
      "Wainriders",
      "Balchoth",
      "Corsairs of Umbar",
      "Black Númenóreans",
    ],
  ),
  ...group(
    "tribe",
    "middle-earth",
    "Dwarven kindreds",
    ["dwarven"],
    ["warden", "balanced"],
    [
      "Longbeards",
      "Firebeards",
      "Broadbeams",
      "Ironfists",
      "Stiffbeards",
      "Blacklocks",
      "Stonefoots",
      "Petty-dwarves",
    ],
  ),
  ...group(
    "tribe",
    "middle-earth",
    "Elven communities",
    ["elven"],
    ["skirmisher", "warden"],
    ["Silvan Elves", "Sindar", "Noldor", "Nandor", "Laiquendi", "Avari"],
  ),
  ...group(
    "tribe",
    "middle-earth",
    "Orc hosts",
    ["darkRealms"],
    ["conqueror", "balanced"],
    ["Moria Orcs", "Misty Mountain Orcs", "Uruk-hai", "Gundabad Orcs"],
  ),
  ...group(
    "regular",
    "westeros",
    "Great houses and former royal houses",
    ["houses", "kingdoms"],
    ["warden", "balanced"],
    [
      "House Stark",
      "House Arryn",
      "House Tully",
      "House Martell",
      "House Royce",
      "House Durrandon",
    ],
  ),
  ...group(
    "regular",
    "westeros",
    "Conquering houses",
    ["houses", "kingdoms"],
    ["conqueror", "rider"],
    [
      "House Targaryen",
      "House Baratheon",
      "House Blackfyre",
      "House Bolton",
      "House Hoare",
    ],
  ),
  ...group(
    "regular",
    "westeros",
    "Wealthy houses and naval lords",
    ["houses"],
    ["merchant", "builder"],
    [
      "House Lannister",
      "House Tyrell",
      "House Hightower",
      "House Manderly",
      "House Gardener",
    ],
  ),
  ...group(
    "regular",
    "westeros",
    "Naval houses",
    ["houses"],
    ["admiral"],
    ["House Greyjoy", "House Velaryon", "House Redwyne"],
  ),
  ...group(
    "regular",
    "westeros",
    "Free cities of Essos",
    ["cities"],
    ["merchant", "diplomat"],
    [
      "Braavos",
      "Pentos",
      "Volantis",
      "Lys",
      "Myr",
      "Tyrosh",
      "Norvos",
      "Qohor",
      "Lorath",
    ],
  ),
  ...group(
    "regular",
    "westeros",
    "Dothraki grasslands",
    ["dothraki"],
    ["conqueror", "rider"],
    ["Dothraki Khalasar"],
  ),
  ...group(
    "regular",
    "westeros",
    "Empires and walled cities of Essos",
    ["essos", "slaverCities"],
    ["conqueror", "engineer"],
    ["Valyrian Freehold", "Old Ghis", "Meereen", "Yunkai", "Astapor", "Sarnor"],
  ),
  ...group(
    "regular",
    "westeros",
    "Eastern trade and imperial cities",
    ["essos", "qarth", "yiTi"],
    ["merchant", "builder", "scholar"],
    ["Qarth", "Yi Ti"],
  ),
  ...group(
    "tribe",
    "westeros",
    "Northern and riverland houses",
    ["houses"],
    ["warden", "balanced"],
    [
      "House Karstark",
      "House Umber",
      "House Glover",
      "House Reed",
      "House Mormont",
      "House Tallhart",
      "House Hornwood",
      "House Dustin",
      "House Ryswell",
      "House Blackwood",
      "House Bracken",
      "House Mallister",
      "House Frey",
      "House Darry",
      "House Vance",
      "House Piper",
      "House Forrester",
    ],
  ),
  ...group(
    "tribe",
    "westeros",
    "Vale, Reach and Dornish houses",
    ["houses"],
    ["warden", "skirmisher", "balanced"],
    [
      "House Dayne",
      "House Yronwood",
      "House Fowler",
      "House Corbray",
      "House Waynwood",
      "House Hunter",
      "House Redfort",
      "House Tarly",
      "House Florent",
      "House Rowan",
      "House Oakheart",
      "House Fossoway",
      "House Dondarrion",
      "House Swann",
      "House Caron",
      "House Selmy",
      "House Peake",
      "House Darklyn",
    ],
  ),
  ...group(
    "tribe",
    "westeros",
    "Island houses and northern clans",
    ["houses", "freeFolk"],
    ["conqueror", "warden", "balanced"],
    [
      "House Harlaw",
      "House Drumm",
      "House Goodbrother",
      "House Botley",
      "House Blacktyde",
      "House Farwynd",
      "House Wull",
      "House Liddle",
      "House Norrey",
      "House Harclay",
      "House Knott",
      "House Flint",
    ],
  ),
  ...group(
    "tribe",
    "westeros",
    "Free folk and mountain clans",
    ["freeFolk", "valeClans"],
    ["conqueror", "skirmisher", "warden"],
    [
      "Thenns",
      "Hornfoots",
      "Nightrunners",
      "Frozen Shore Clans",
      "Ice-river Clans",
      "Cave Dwellers",
      "Burned Men",
      "Stone Crows",
      "Moon Brothers",
      "Black Ears",
      "Painted Dogs",
      "Milk Snakes",
      "Howlers",
      "Redsmiths",
      "Sons of the Mist",
      "Sons of the Tree",
    ],
  ),
];
export const FACTION = new Map(FACTIONS.map((f) => [f.id, f]));
