const fs=require('node:fs/promises'),path=require('node:path');
(async()=>{
const root=__dirname,manifest=JSON.parse(await fs.readFile(path.join(root,'Defense-Manifest.json'),'utf8'));
const data=JSON.stringify(manifest).replaceAll('<','\\u003c');
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Modern Defense — Age of Fronts</title>
<style>
:root{color-scheme:dark;font-family:Inter,Segoe UI,sans-serif;background:#131918;color:#e3e8df}*{box-sizing:border-box}body{margin:0}header{padding:28px 4vw 20px;border-bottom:1px solid #37453b;background:#1b2420}h1{font-size:30px;letter-spacing:-.6px;margin:0 0 8px}p{color:#aebdb1;line-height:1.5}a{color:#d4cb92}header p{max-width:860px;margin:8px 0}.toolbar{display:flex;gap:12px;flex-wrap:wrap;align-items:center;margin:20px 0 0}select,button{font:inherit;color:inherit;background:#28372d;border:1px solid #4b6050;border-radius:7px;padding:9px 12px;cursor:pointer}button:hover,button.active{background:#63734d;color:white}main{padding:24px 4vw}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:22px}.card{border:1px solid #3a4b3e;border-radius:12px;background:#1d2721;overflow:hidden}.card h2{font-size:18px;line-height:1.2;min-height:44px;margin:18px 18px 4px}.card .sub{margin:0 18px 12px;font-size:13px}.stage{height:325px;display:flex;align-items:center;justify-content:center;background-color:#252e28;background-image:conic-gradient(#2b352d 25%,transparent 0 50%,#2b352d 0 75%,transparent 0);background-size:24px 24px;position:relative}.stage>img{width:100%;height:100%;object-fit:contain}.clips{display:flex;gap:6px;flex-wrap:wrap;padding:12px 16px}.clips button{font-size:13px;padding:7px 10px}.downloads{padding:0 18px 16px;display:flex;gap:12px;flex-wrap:wrap;font-size:13px}.linked{padding:12px 16px;border-top:1px solid #3a4b3e;display:grid;grid-template-columns:1fr 1fr;gap:12px}.linked img{width:100%;height:125px;object-fit:contain;background:#18201c}.linked figcaption{font-size:12px;line-height:1.4;color:#b8c5b9}figure{margin:0}.demo{border:1px solid #495d4a;border-radius:12px;background:#1c2920;margin:0 0 24px;overflow:hidden}summary{cursor:pointer;padding:16px;font-weight:600;color:#d3ddb9}.demo-head{display:flex;gap:14px;align-items:center;flex-wrap:wrap;padding:16px}.demo-head h2{margin:0;font-size:19px}.demo canvas{width:100%;max-height:510px;object-fit:contain;display:block;background:#18251e}.demo p{margin:12px 16px;font-size:13px}.light .stage{background-color:#d6dacb;background-image:conic-gradient(#eef0e7 25%,transparent 0 50%,#eef0e7 0 75%,transparent 0)}.plain .stage{background:#34462f}.empty{padding:30px}footer{padding:30px 4vw;color:#98aa9c;font-size:13px}#count{color:#c4ccb7}#phase{font-size:13px;color:#c8d4b6}
</style><header><h1>Modern Defense</h1><p>Overhead RTS proposals: MIRV launch complex, twin-cannon anti-air vehicle, wheeled SAM and interceptor Humvee. North-facing artwork with separate projectile and impact animations.</p><div class="toolbar"><label>Show <select id="filter"><option value="all">All assets</option><option value="units" selected>Vehicles & silo</option><option value="projectile">Projectiles</option><option value="effect">Impact effects</option></select></label><label>Background <select id="background"><option value="checker">Dark checker</option><option value="light">Light checker</option><option value="plain">Field green</option></select></label><span id="count"></span><a href="../Weapon-Review.html">Earlier weapons</a><a href="../../Building%20Icons/Top-Down-Correction-Review.html">Building collection</a></div></header><main><details class="demo"><summary>Play a firing sequence</summary><div class="demo-head"><h2>Firing sequence</h2><select id="demo-unit"></select><button id="play">Play sequence</button><span id="phase">Ready</span></div><canvas id="demo" width="1100" height="510"></canvas><p>Presentation preview only. Projectiles travel between sprites; the MIRV carrier separates into three warheads, each producing a nuclear flash, shockwave and lingering smoke.</p></details><div class="grid" id="grid"></div></main><footer>Transparent PNG frame sequences, lossless sprite sheets, looping WebP previews and one-shot WebP clips. Buildings 1254 × 1254; vehicles and projectiles 627 × 627; impacts 314 × 314. Painted keyposes with proposed timings; movement clips animate in place. <a href="Defense-Manifest.json">Manifest</a> · <a href="Generation-Manifest.json">Exact prompts</a> · <a href="Defense-Validation.json">Export validation</a></footer>
<script>
const manifest=${data},assets=manifest.assets,byKey=Object.fromEntries(assets.map(a=>[a.key,a]));
const url=(a,file)=>a.directory+'/'+file,preview=(a,name)=>url(a,a.animations[name].preview),title=n=>n[0].toUpperCase()+n.slice(1),grid=document.querySelector('#grid');
function render(){const f=document.querySelector('#filter').value,shown=assets.filter(a=>f==='all'||f==='units'&&['vehicle','building'].includes(a.type)||a.type===f);grid.replaceChildren();document.querySelector('#count').textContent=shown.length+' assets';for(const a of shown){
const names=Object.keys(a.animations),defaultName=a.type==='building'?'launch':a.type==='vehicle'?'attack':names[0],card=document.createElement('article');card.className='card';
const h=document.createElement('h2');h.textContent=a.label;card.append(h);const sub=document.createElement('p');sub.className='sub';sub.textContent='Modern · '+a.dimension+' × '+a.dimension+' · '+names.length+' clip'+(names.length>1?'s':'');card.append(sub);
const stage=document.createElement('div');stage.className='stage';const img=document.createElement('img');img.alt=a.label;img.src=preview(a,defaultName);stage.append(img);card.append(stage);
const buttons=document.createElement('div');buttons.className='clips';const downloads=document.createElement('div');downloads.className='downloads';function choose(name){img.src=preview(a,name);for(const b of buttons.children)b.classList.toggle('active',b.dataset.name===name);downloads.replaceChildren();for(const [label,file] of [['Icon','Icon.png'],['First frame',a.animations[name].frames[0].file],['Sprite sheet',a.animations[name].files[0]],['Metadata','animations.json'],['Source art','SourceArt/']]){const l=document.createElement('a');l.href=url(a,file);l.textContent=label;l.target='_blank';downloads.append(l);}}
for(const name of names){const b=document.createElement('button');b.dataset.name=name;b.textContent=title(name);b.onclick=()=>choose(name);buttons.append(b);}card.append(buttons,downloads);choose(defaultName);
if(a.type==='vehicle'||a.type==='building'){const linked=document.createElement('div');linked.className='linked';for(const key of [a.links.projectile,a.links.effect]){const child=byKey[key];if(!child)continue;const fig=document.createElement('figure'),im=document.createElement('img'),cap=document.createElement('figcaption');im.src=preview(child,Object.keys(child.animations)[0]);im.alt=child.label;cap.textContent=child.label;fig.append(im,cap);linked.append(fig);}card.append(linked);}grid.append(card);}}
document.querySelector('#filter').onchange=render;document.querySelector('#background').onchange=e=>{document.body.classList.remove('light','plain');if(e.target.value!=='checker')document.body.classList.add(e.target.value);};render();
const select=document.querySelector('#demo-unit'),canvas=document.querySelector('#demo'),ctx=canvas.getContext('2d'),phase=document.querySelector('#phase'),cache=new Map();
for(const a of assets.filter(a=>['vehicle','building'].includes(a.type))){const o=document.createElement('option');o.value=a.key;o.textContent=a.label;select.append(o);}select.value='MIRVLaunchComplex';
function getImage(src){if(!cache.has(src)){const im=new Image();im.src=src;cache.set(src,im);}return cache.get(src);}
function clipImage(a,name,t){const c=a.animations[name];let elapsed=0;for(const f of c.frames){elapsed+=f.durationMs;if(t<elapsed)return getImage(url(a,f.file));}return getImage(url(a,c.frames[c.frames.length-1].file));}
function draw(im,x,y,w,angle=0){if(!im.complete||!im.naturalWidth)return;ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.drawImage(im,-w/2,-w/2,w,w);ctx.restore();}
function field(){ctx.clearRect(0,0,1100,510);ctx.fillStyle='#18251e';ctx.fillRect(0,0,1100,510);ctx.strokeStyle='#293e2d';ctx.lineWidth=1;for(let x=0;x<1100;x+=55){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,510);ctx.stroke();}for(let y=0;y<510;y+=55){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(1100,y);ctx.stroke();}}
function ready(){field();draw(getImage(url(byKey[select.value],'Icon.png')),550,387,220);phase.textContent='Ready';}select.onchange=ready;let run=0;
document.querySelector('#play').onclick=async()=>{const token=++run,a=byKey[select.value],p=byKey[a.links.projectile],e=byKey[a.links.effect],isMirv=a.type==='building',war=byKey.MIRVWarhead;phase.textContent='Loading frames…';const wanted=[a,p,e,...(isMirv?[war]:[])];for(const x of wanted)for(const c of Object.values(x.animations))for(const f of c.frames)getImage(url(x,f.file));await Promise.all([...cache.values()].filter(im=>!im.complete).map(im=>new Promise(resolve=>{im.onload=resolve;im.onerror=resolve;})));if(token!==run)return;const start=performance.now();function tick(now){if(token!==run)return;const t=now-start;field();draw(clipImage(a,isMirv?'launch':'attack',t),550,387,220);if(isMirv){const targets=[270,550,830];for(const x of targets){ctx.strokeStyle='#859272';ctx.beginPath();ctx.arc(x,102,25,0,Math.PI*2);ctx.stroke();}if(t>=1000&&t<1800){draw(clipImage(p,'flight',(t-1000)%1000),550,330-(t-1000)/800*135,150);phase.textContent='Carrier launch';}else if(t>=1800&&t<3133){draw(clipImage(p,'separation',t-1800),550,190,215);phase.textContent='Three-warhead separation';}else if(t>=3133&&t<3950){const u=(t-3133)/817;targets.forEach((x,i)=>draw(clipImage(war,'flight',(t-3133)%1000),550+(x-550)*u,190-88*u,100,(i-1)*.65));phase.textContent='Three independent warheads';}else if(t>=3950){targets.forEach((x,i)=>{const age=t-3950-i*110;if(age>=0)draw(clipImage(e,'detonate',age),x,102,245);});phase.textContent=t<6500?'Nuclear flashes & shockwaves':'Lingering smoke';}}else{ctx.strokeStyle='#859272';ctx.beginPath();ctx.arc(550,110,28,0,Math.PI*2);ctx.stroke();if(t>=350&&t<1150){draw(clipImage(p,'flight',(t-350)%1000),550,295-(t-350)/800*185,145);phase.textContent='Projectile flight';}else if(t>=1150){draw(clipImage(e,'detonate',t-1150),550,110,225);phase.textContent='Interception impact';}}
const end=isMirv?10400:1150+e.animations.detonate.durationMs+450;if(t<end)requestAnimationFrame(tick);else{phase.textContent='Complete';draw(getImage(url(a,'Icon.png')),550,387,220);}}requestAnimationFrame(tick);};
getImage(url(byKey[select.value],'Icon.png')).onload=ready;ready();
</script></html>`;
await fs.writeFile(path.join(root,'Modern-Defense-Review.html'),html);console.log('Created Modern-Defense-Review.html with '+manifest.assets.length+' assets');
})().catch(e=>{console.error(e);process.exitCode=1;});
