const {chromium}=require("C:/Users/Damien/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright"),fs=require("fs"),assert=require("assert/strict");const out="Art/Cultures/Russians/Buildings/Animations";(async()=>{const browser=await chromium.launch({headless:true,channel:"msedge"});try{const page=await browser.newPage({viewport:{width:1450,height:1300}}),errors=[];page.on("pageerror",e=>errors.push(e.message));const url="http://127.0.0.1:9000/Art/Cultures/Russians/Buildings/Animations/Review.html";await page.goto(url);await page.locator('#catalog[aria-busy="false"]').waitFor({state:"attached"});assert.equal(await page.locator("#catalog article").count(),4);assert.equal(await page.locator("#catalog canvas").count(),16);assert.match(await page.locator("#status").textContent(),/4 weapons loaded/);
await page.locator("#play").click();assert.equal(await page.locator("#play").textContent(),"Play");const checks=[];
const frame=async n=>{await page.locator("#frame").evaluate((el,n)=>{el.value=String(n);el.dispatchEvent(new Event("input",{bubbles:true}));},n);};
const hashes=()=>page.locator(".stage canvas").evaluateAll(cs=>cs.map(c=>{const p=c.getContext("2d").getImageData(0,0,c.width,c.height).data;let h=2166136261,alpha=0;for(let i=0;i<p.length;i++){h=Math.imul(h^p[i],16777619);if(i%4===3)alpha+=p[i];}return {hash:h>>>0,alpha,frame:c.dataset.frame,facing:c.dataset.facing};}));
for(const facing of ["N","E","S","W"]){await page.locator("#facing").selectOption(facing);await page.locator('#catalog[aria-busy="false"]').waitFor({state:"attached"});assert.equal(await page.locator("#catalog article").count(),4);await frame(0);const a=await hashes();await frame(2);const b=await hashes();assert(a.every((x,i)=>x.hash!==b[i].hash&&x.alpha>0&&b[i].facing===facing));checks.push({facing,loadedWeapons:4,animatedCanvases:a.length,distinctFramePixels:true});}
await page.locator("#facing").selectOption("N");await page.locator('#catalog[aria-busy="false"]').waitFor({state:"attached"});await frame(0);for(const bg of ["checker","light","dark"]){await page.locator("#background").selectOption(bg);await page.screenshot({path:out+"/Review-"+bg+".png",fullPage:true});}
await page.locator("#play").click();const before=await hashes();await page.waitForTimeout(210);const after=await hashes();assert(before.some((x,i)=>x.hash!==after[i].hash));await page.locator("#play").click();const paused=await hashes();await page.waitForTimeout(150);assert.deepEqual(await hashes(),paused);
await page.locator("#speed").selectOption("0.5");await page.locator("#restart").click();assert.match(await page.locator("#frame-label").textContent(),/Frame 1 /);
for(const age of ["EarlyModern","Modern"]){await page.locator("#age").selectOption(age);await page.locator('#catalog[aria-busy="false"]').waitFor({state:"attached"});assert.equal(await page.locator("#catalog article").count(),2);for(const weapon of ["Anti-Aircraft Emplacement","Gun Nest"]){await page.locator("#weapon").selectOption(weapon);await page.locator('#catalog[aria-busy="false"]').waitFor({state:"attached"});assert.equal(await page.locator("#catalog article").count(),1);assert.equal(await page.locator("#catalog canvas").count(),4);}await page.locator("#weapon").selectOption("");await page.locator('#catalog[aria-busy="false"]').waitFor({state:"attached"});}
await page.goto("http://127.0.0.1:9000/Art/Building%20Icons/Top-Down-Correction-Review.html?civ=russians");await page.locator('#catalog[aria-busy="false"]').waitFor({state:"attached"});const links=page.locator("#catalog a").filter({hasText:"Shooting animation"});assert.equal(await links.count(),4);const galleryLinks=await links.evaluateAll(xs=>xs.map(a=>a.href));await links.first().click();await page.locator('#catalog[aria-busy="false"]').waitFor({state:"attached"});assert.equal(await page.locator("#catalog article").count(),1);assert.equal(errors.length,0);
fs.writeFileSync(out+"/Browser-Validation.json",JSON.stringify({date:"2026-10-07",passed:true,method:"Separate local headless Edge",directionChecks:checks,ageAndWeaponFilters:true,playbackChangesPixels:true,pauseStopsPlayback:true,scrubAndRestart:true,livePreviewSizes:[48,64,128],backgrounds:["checker","light","dark"],galleryLinks,pageErrors:errors,scope:"Local art review only; no gameplay integration or user artistic approval"},null,2)+"\n");console.log("Browser checks passed: all 16 directional clips, live preview sizes, playback/pause, scrub, filters and four building-card links.");}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});