const fs = require('node:fs');
const path = require('node:path');
const root = __dirname;
const manifest = JSON.parse(fs.readFileSync(path.join(root,'Weapon-Manifest.json'),'utf8'));
const data = manifest.units.map(u=>({key:u.key,label:u.label,age:u.age,category:u.category,directory:u.directory,clips:Object.fromEntries(Object.entries(u.animations).map(([k,v])=>[k,{count:v.frameCount,duration:v.durationMs,sheet:v.file,preview:v.preview,frames:v.frames.map(f=>f.file)}]))}));
const html = `<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Age of Fronts · Weapon proposals</title>
<style>
:root{font-family:Inter,Segoe UI,Arial,sans-serif;color:#eae7df;background:#141b22;color-scheme:dark}*{box-sizing:border-box}body{margin:0}header{padding:32px 4vw 20px;border-bottom:1px solid #34414d}h1{font-size:30px;font-weight:600;margin:6px 0 10px}header p{max-width:820px;color:#b7c2ca;line-height:1.55;margin:6px 0}a{color:#a9d3ed}label{font-size:13px;color:#c2ccd3}select,button{font:inherit;border:1px solid #435260;border-radius:6px;background:#24313d;color:#f2f1e9;padding:8px 11px;cursor:pointer}button:hover,button.active{background:#3b5365;border-color:#92bdca}nav{position:sticky;top:0;z-index:3;background:#1a252f;padding:12px 4vw;display:flex;flex-wrap:wrap;gap:12px;align-items:end;border-bottom:1px solid #3c4b59}nav label{display:grid;gap:5px}.count{margin-left:auto;font-size:14px;color:#b8c7d0}main{padding:24px 4vw;display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:20px}.card{border:1px solid #34414d;border-radius:10px;overflow:hidden;background:#1d2831}.canvas{position:relative;aspect-ratio:1;display:grid;place-items:center;background:#24313b;overflow:hidden}.canvas img{display:block;width:100%;height:100%;object-fit:contain}.canvas:after{content:'↑ Forward';position:absolute;top:10px;left:12px;color:#c3d4dd;font-size:11px;pointer-events:none}.info{padding:16px}h2{margin:0 0 5px;font-size:21px}.meta{color:#aebdc7;font-size:13px}.buttons{display:flex;flex-wrap:wrap;gap:6px;margin:12px 0}button{font-size:12px}.frames{display:flex;align-items:center;gap:8px;font-size:12px;color:#b9c8d0}.frames input{flex:1;min-width:50px}.links{margin-top:12px;display:flex;flex-wrap:wrap;gap:10px;font-size:12px}.bg-light .canvas{background:#e5e5de}.bg-light .canvas:after{color:#3c4b56}.bg-checker .canvas{background-color:#b8bdc2;background-image:linear-gradient(45deg,#879199 25%,transparent 25%),linear-gradient(-45deg,#879199 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#879199 75%),linear-gradient(-45deg,transparent 75%,#879199 75%);background-size:24px 24px;background-position:0 0,0 12px,12px -12px,-12px 0}.empty{padding:25px;color:#aabcc8}footer{padding:12px 4vw 30px;color:#9eb0bd;font-size:13px}@media(min-width:1450px){main{grid-template-columns:repeat(4,1fr)}}
</style>
<body><header><div>AGE OF FRONTS · PROPOSED UNIT ART</div><h1>Weapons across the ages</h1><p>12 crewed units · 627 × 627 transparent frames · one upward-facing set per unit. Inspect idle, movement and attack on dark, light or checkerboard backgrounds.</p><p>Each clip uses four painted key poses with explicit timing. Movement plays in place. Attack is a single cycle; its preview repeats with a short pause. These are animation proposals for review.</p><p><a href="Weapon-Manifest.json">Asset manifest</a> · <a href="Generation-Manifest.json">Exact generation prompts</a> · <a href="Weapons-Validation.json">Validation</a> · <a href="../Building%20Icons/Top-Down-Correction-Review.html">Buildings</a></p></header>
<nav><label>Category<select id="category"><option value="all">All weapons</option><option>Field Artillery</option><option>Siege Weapons</option></select></label><label>Age<select id="age"><option value="all">All ages</option><option value="BronzeAge">Bronze Age</option><option value="ClassicalAge">Classical Age</option><option value="EarlyMedieval">Early Medieval</option><option value="LateMedieval">Late Medieval</option><option value="EarlyModern">Early Modern</option><option value="Modern">Modern</option></select></label><label>Animation<select id="animation"><option value="icon">Still icon</option><option value="idle">Idle</option><option value="movement">Movement</option><option value="attack">Attack</option></select></label><label>Background<select id="background"><option value="dark">Dark</option><option value="light">Light</option><option value="checker">Checkerboard</option></select></label><span id="count" class="count"></span></nav><main id="units"></main><footer>Camera: vertical overhead · Facing: screen up · Pivot: center (313.5, 313.5) · Sprite sheets: six columns · Frames: 12 fps · Alpha: straight</footer>
<script>
const units=${JSON.stringify(data).replaceAll('<','\\u003c')};
const ages={BronzeAge:'Bronze Age',ClassicalAge:'Classical Age',EarlyMedieval:'Early Medieval',LateMedieval:'Late Medieval',EarlyModern:'Early Modern',Modern:'Modern'};
const controls={category:document.querySelector('#category'),age:document.querySelector('#age'),animation:document.querySelector('#animation'),background:document.querySelector('#background')};
const encoded=p=>p.split('/').map(encodeURIComponent).join('/');
const params=new URLSearchParams(location.search);for(const k of ['category','age','animation','background'])if(params.has(k)&&[...controls[k].options].some(o=>o.value===params.get(k)))controls[k].value=params.get(k);
function show(){
 document.body.className='bg-'+controls.background.value;
 const selected=units.filter(u=>(controls.category.value==='all'||u.category===controls.category.value)&&(controls.age.value==='all'||u.age===controls.age.value));
 document.querySelector('#count').textContent=selected.length+' / '+units.length+' units';
 const main=document.querySelector('#units');main.replaceChildren();
 for(const u of selected){
  const card=document.createElement('article');card.className='card';card.dataset.key=u.key;
  const canvas=document.createElement('div');canvas.className='canvas';const img=document.createElement('img');img.alt=u.label+' from directly above';img.width=627;img.height=627;canvas.append(img);
  const info=document.createElement('div');info.className='info';const title=document.createElement('h2');title.textContent=u.label;const meta=document.createElement('div');meta.className='meta';meta.textContent=ages[u.age]+' · '+u.category;info.append(title,meta);
  const buttons=document.createElement('div');buttons.className='buttons';const sliderRow=document.createElement('div');sliderRow.className='frames';const slider=document.createElement('input');slider.type='range';slider.min=0;slider.step=1;slider.setAttribute('aria-label',u.label+' frame');const position=document.createElement('span');sliderRow.append(slider,position);
  const links=document.createElement('div');links.className='links';let active='icon';
  const link=(label,file)=>{const a=document.createElement('a');a.textContent=label;a.href=encoded(u.directory+'/'+file);links.append(a)};
  function change(clip,once=false){active=clip;img.src=encoded(u.directory+'/'+(clip==='icon'?'Icon.png':once?'Attack-OneShot.webp':u.clips[clip].preview))+(once?'?play='+Date.now():'');for(const b of buttons.children)b.classList.toggle('active',b.dataset.clip===clip&&!once);slider.disabled=clip==='icon';slider.max=clip==='icon'?0:u.clips[clip].count-1;slider.value=0;position.textContent=clip==='icon'?'Still':u.clips[clip].count+' frames · '+(u.clips[clip].duration/1000)+' s';links.replaceChildren();link('Icon PNG','Icon.png');if(clip!=='icon')link('Sprite sheet',u.clips[clip].sheet);link('Frames','Frames/');link('Metadata','animations.json');link('Prompts','generation-prompts.json')}
  for(const [clip,label] of [['icon','Still'],['idle','Idle'],['movement','Move'],['attack','Attack']]){const b=document.createElement('button');b.textContent=label;b.dataset.clip=clip;b.onclick=()=>change(clip);buttons.append(b)}const once=document.createElement('button');once.textContent='Attack once';once.onclick=()=>change('attack',true);buttons.append(once);
  slider.oninput=()=>{if(active==='icon')return;img.src=encoded(u.directory+'/'+u.clips[active].frames[Number(slider.value)]);position.textContent='Frame '+(Number(slider.value)+1)+' / '+u.clips[active].count;for(const b of buttons.children)b.classList.remove('active')};
  info.append(buttons,sliderRow,links);card.append(canvas,info);main.append(card);change(controls.animation.value);
 }
 if(!selected.length){const p=document.createElement('p');p.className='empty';p.textContent='No weapon proposals for this selection.';main.append(p)}
 const query=new URLSearchParams();for(const k of Object.keys(controls))if(!['all','icon','dark'].includes(controls[k].value))query.set(k,controls[k].value);history.replaceState(null,'',location.pathname+(query.size?'?'+query:''));
}
Object.values(controls).forEach(c=>c.addEventListener('change',show));show();
</script></body></html>`;
fs.writeFileSync(path.join(root,'Weapon-Review.html'),html);
console.log('Review gallery: '+data.length+' units');
