const fs = require('node:fs');
const path = require('node:path');
const root = __dirname;
const manifest = JSON.parse(fs.readFileSync(path.join(root,'Weapon-Manifest.json'),'utf8'));
const data = manifest.units.map(u=>({key:u.key,label:u.label,age:u.age,category:u.category,directory:u.directory,clips:Object.fromEntries(Object.entries(u.animations).map(([k,v])=>[k,{count:v.frameCount,duration:v.durationMs,sheet:v.file,preview:v.preview,frames:v.frames.map(f=>f.file)}]))}));
const html = `<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Age of Fronts · Weapon proposals</title>
<style>
:root{font-family:Inter,Segoe UI,Arial,sans-serif;color:#eae7df;background:#141b22;color-scheme:dark}*{box-sizing:border-box}body{margin:0}header{padding:32px 4vw 20px;border-bottom:1px solid #34414d}h1{font-size:30px;font-weight:600;margin:6px 0 10px}header p{max-width:820px;color:#b7c2ca;line-height:1.55;margin:6px 0}a{color:#a9d3ed}label{font-size:13px;color:#c2ccd3}select,button{font:inherit;border:1px solid #435260;border-radius:6px;background:#24313d;color:#f2f1e9;padding:8px 11px;cursor:pointer}button:hover,button.active{background:#3b5365;border-color:#92bdca}nav{position:sticky;top:0;z-index:3;background:#1a252f;padding:12px 4vw;display:flex;flex-wrap:wrap;gap:12px;align-items:end;border-bottom:1px solid #3c4b59}nav label{display:grid;gap:5px}.count{margin-left:auto;font-size:14px;color:#b8c7d0}main{padding:24px 4vw;display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:20px}.card{border:1px solid #34414d;border-radius:10px;overflow:hidden;background:#1d2831}.canvas{position:relative;aspect-ratio:1;display:grid;place-items:center;background:#24313b;overflow:hidden}.canvas img{display:block;width:100%;height:100%;object-fit:contain}.canvas:after{content:'↑ Forward';position:absolute;top:10px;left:12px;color:#c3d4dd;font-size:11px;pointer-events:none}.info{padding:16px}h2{margin:0 0 5px;font-size:21px}.meta{color:#aebdc7;font-size:13px}.buttons{display:flex;flex-wrap:wrap;gap:6px;margin:12px 0}button{font-size:12px}.frames{display:flex;align-items:center;gap:8px;font-size:12px;color:#b9c8d0}.frames input{flex:1;min-width:50px}.links{margin-top:12px;display:flex;flex-wrap:wrap;gap:10px;font-size:12px}.bg-light .canvas{background:#e5e5de}.bg-light .canvas:after{color:#3c4b56}.bg-checker .canvas{background-color:#b8bdc2;background-image:linear-gradient(45deg,#879199 25%,transparent 25%),linear-gradient(-45deg,#879199 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#879199 75%),linear-gradient(-45deg,transparent 75%,#879199 75%);background-size:24px 24px;background-position:0 0,0 12px,12px -12px,-12px 0}.empty{padding:25px;color:#aabcc8}footer{padding:12px 4vw 30px;color:#9eb0bd;font-size:13px}@media(min-width:1450px){main{grid-template-columns:repeat(4,1fr)}}
.catalog-links{display:flex;flex-wrap:wrap;gap:14px}.culture-tabs{display:flex;gap:8px;padding:12px 4vw;background:#19232d;border-bottom:1px solid #34414d}.culture-tabs [aria-selected=true]{background:#c0634f;color:#fff;border-color:#dd8a74}.culture-tabs button:focus-visible{outline:2px solid #e5c39f;outline-offset:3px}
</style>
<body><header><div>AGE OF FRONTS · PROPOSED UNIT ART</div><h1>Weapons across the ages</h1><p id="catalog-summary">12 crewed units · 627 × 627 transparent frames · one upward-facing set per unit. Inspect idle, movement and attack on dark, light or checkerboard backgrounds.</p><p id="clip-notes">Each clip uses four painted key poses with explicit timing. Movement plays in place. Attack is a single cycle; its preview repeats with a short pause. These are animation proposals for review.</p><p class="catalog-links"><a id="manifest-link" href="Weapon-Manifest.json">Asset manifest</a><a id="prompts-link" href="Generation-Manifest.json">Exact generation prompts</a><a id="validation-link" href="Weapons-Validation.json">Validation</a><a id="soldiers-link" href="../Soldier%20Icons/StoneAge_Animation_Preview.html">Soldiers</a></p></header>
<div class="culture-tabs" id="cultures" role="tablist" aria-label="Civilization"></div>
<nav><label>Category<select id="category"><option value="all">All weapons</option><option>Field Artillery</option><option>Siege Weapons</option></select></label><label>Age<select id="age"><option value="all">All ages</option><option value="BronzeAge">Bronze Age</option><option value="ClassicalAge">Classical Age</option><option value="EarlyMedieval">Early Medieval</option><option value="LateMedieval">Late Medieval</option><option value="EarlyModern">Early Modern</option><option value="Modern">Modern</option></select></label><label>Animation<select id="animation"><option value="icon">Still icon</option><option value="idle">Idle</option><option value="movement">Movement</option><option value="attack">Attack</option></select></label><label>Background<select id="background"><option value="dark">Dark</option><option value="light">Light</option><option value="checker">Checkerboard</option></select></label><span id="count" class="count"></span></nav><main id="units" role="tabpanel" aria-busy="true"></main><footer id="artwork-contract">Camera: vertical overhead · Facing: screen up · Pivot: center (313.5, 313.5) · Sprite sheets: six columns · Frames: 12 fps · Alpha: straight</footer>
<script type="module" src="weapon-review.js"></script></body></html>`;
fs.writeFileSync(path.join(root,'Weapon-Review.html'),html);
console.log('Review gallery: '+data.length+' units');
