const fs=require('fs'),path=require('path'),crypto=require('crypto');
const sharp=require('C:/Users/Damien/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root=process.cwd(),out=path.resolve('Art/Cultures/Russians/FactionMasks/StoneAge');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
// Exact-coordinate material masks. Red cloth seeds distinguish fabric from warm skin,
// brown leather, chestnut coats and the low-alpha red glow in the Clubman source.
function segment(data,w,h,unit){const n=w*h,candidate=new Uint8Array(n),seed=new Uint8Array(n),seen=new Uint8Array(n),result=new Uint8Array(n);
for(let i=0;i<n;i++){let j=i*4,r=data[j],g=data[j+1],b=data[j+2],a=data[j+3];candidate[i]=a>=180&&r>=18&&r>g*1.45&&r>b*1.4&&Math.abs(g-b)<Math.max(12,r*.13)?1:0;seed[i]=candidate[i]&&a>=240&&r>g*1.9&&r>b*1.8?1:0}
for(let i=0;i<n;i++){if(!candidate[i]||seen[i])continue;let queue=[i],seeds=0;seen[i]=1;for(let k=0;k<queue.length;k++){const p=queue[k];seeds+=seed[p];for(const q of [p%w?p-1:-1,p%w<w-1?p+1:-1,p-w,p+w]){if(q>=0&&q<n&&candidate[q]&&!seen[q]){seen[q]=1;queue.push(q)}}}if(queue.length>=256&&seeds/queue.length>=(unit==="Clubman"?0.88:0.8))for(const p of queue)result[p]=data[p*4+3]}
return result}
(async()=>{fs.mkdirSync(out,{recursive:true});const c=JSON.parse(fs.readFileSync('Art/Cultures/Russians/Troops.json'));const manifest={schemaVersion:1,age:'StoneAge',status:'awaiting-user-visual-review',maskEncoding:'White RGBA; alpha selects faction-colored material. Same pixel dimensions as source. Zero alpha preserves original material.',scope:'Selected gallery assets only; source sprites and gameplay unchanged.',units:[]};
for(const u of c.units.filter(u=>u.age==='StoneAge')){const metadata=path.resolve('Art/Cultures/Russians',u.metadata),d=JSON.parse(fs.readFileSync(metadata)),name=path.basename(path.dirname(metadata))==='TopDownReview'?path.basename(path.dirname(path.dirname(metadata))):path.basename(path.dirname(metadata));const dir=path.join(out,name);fs.mkdirSync(dir,{recursive:true});const files=[...new Set(d.animations.flatMap(a=>[a.file,a.corpseFile,...a.frames.map(f=>f.sheet)].filter(Boolean)))];const entry={id:u.id,name,metadata:path.relative(out,metadata).replaceAll('\\','/'),metadataHash:sha(fs.readFileSync(metadata)),materials:['red cap','red tunic and sleeves',...(name==='Scout'?['red saddle panel when exposed']:[])],preserved:['fur','skin','trousers','boots and straps','weapon',...(name==='Scout'?['horse coat, mane and tack']:[])],sheets:[]};
for(const f of files){const p=path.resolve(path.dirname(metadata),f),sourceBytes=fs.readFileSync(p),{data,info}=await sharp(sourceBytes).ensureAlpha().raw().toBuffer({resolveWithObject:true}),selection=segment(data,info.width,info.height,name),mask=Buffer.alloc(info.width*info.height*4);let selected=0;for(let i=0;i<selection.length;i++){mask[i*4]=mask[i*4+1]=mask[i*4+2]=255;mask[i*4+3]=selection[i];if(selection[i])selected++}const maskFile=name+'/'+path.basename(f,'.png')+'.faction-mask.png';await sharp(mask,{raw:{width:info.width,height:info.height,channels:4}}).png().toFile(path.join(out,maskFile));if(sha(fs.readFileSync(p))!==sha(sourceBytes))throw Error('Source changed');entry.sheets.push({file:f,source:path.relative(out,p).replaceAll('\\','/'),sourceHash:sha(sourceBytes),mask:maskFile,width:info.width,height:info.height,maskedPixels:selected});console.log(name+' '+f+' '+selected)}manifest.units.push(entry)}
fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');console.log('Saved '+manifest.units.reduce((n,u)=>n+u.sheets.length,0)+' masks');})().catch(e=>{console.error(e);process.exitCode=1});



